### PR TITLE
Arweave URL option

### PR DESCRIPTION
**Pull request by martonlederer**
This PR adds a menu to choose between a `nest.land` and an Arweave import URL.

### CODE REVIEW

**Comment by martonlederer** [comment]
I'm not sure why the linting is failing, but I'd love to hear your opinion on this @t8

**Comment by t8** [comment]
I'm not sure why lining is failing either, but adding my review now @martonlederer!

**Review by t8 — CHANGES_REQUESTED** [review]
So so excited to see this addition. Amazing work @martonlederer! I do have a few small things to give feedback on though:

1) Could we change the background of the tooltip here? Perhaps a slightly lighter green with white text or a dark grey background with white text?
2) I think the text in the tooltip should say something like: `You can choose to import your module from Arweave directly, which will remove your dependence on x.nest.land.`

image

**Review by t8 — APPROVED** [review]
LGTM!

**Pull request merged**
