### PR TITLE
[FEAT] Dynamic favicon

### PR DESCRIPTION
**Pull request by jletey**
**Before:**

| Light Mode | Dark Mode |
| --- | --- |
| Screenshot 2020-07-21 at 08 34 39 | Screenshot 2020-07-21 at 08 30 14 |

**After:**

| Light Mode | Dark Mode |
| --- | --- |
| Screenshot 2020-07-21 at 08 38 34 | Screenshot 2020-07-21 at 08 38 20 |

Screen Recording 2020-07-21 at 15 49 32

## Notes

I had to adjust the size of the `logo_light.svg` and `logo_dark.svg` files, as they were of size 100x75, which didn't scale well. The new files are in `favicon_light.svg` and `favicon_dark.svg` 😝 They both have size 100x100.

### CODE REVIEW

**Comment by zorbyte** [comment]
Will this cause issues with browsers that do not look for this kind of metadata? I'm assuming it'll just pick one of them.

**Comment by jletey** [comment]
@zorbyte Yeah I would assume 🤔 Although this is pretty generally supported:

Screenshot 2020-07-21 at 09 18 03

**Comment by MartonDev** [comment]
Good question. But our service is  for developers, who usually always use modern tools, so I wouldn't worry about it

**Comment by jletey** [comment]
Awesome, glad everyone likes it 😄 Should we do anything about the linter.

Also, I don't have merge access so someone else will have to do that.

**Comment by MartonDev** [comment]
Yeah, is it necessary to put the script at the top? Or is there an npm version of it?

**Comment by t8** [comment]
It looks like the linter is upset about the webpack variables in `index.html`. I'm going to merge this anyway and we can create another PR to fix the linter if necessary.

**Pull request merged**
